const SECTION_ORDER=["Latest IAM Trends","Top Security Vendors","Emerging Threats","Market Share Insights","Technology Developments","Competitive Analysis"];
const QUESTIONS={"Latest IAM Trends":"What are the latest trends in Identity & Access Management?","Top Security Vendors":"Who are the leading vendors in the Security & IAM market?","Emerging Threats":"What new threats are emerging in the Security & IAM space?","Market Share Insights":"Can you provide market share insights for IAM solutions?","Technology Developments":"What are the recent technology developments in Security & IAM?","Competitive Analysis":"How do major IAM vendors compare in terms of features and market presence?"};
const state={items:[],search:"",section:"All"};
const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})};
async function load(){const r=await fetch("data/news.json",{cache:"no-store"});const d=await r.json();state.items=d.items||[];document.getElementById("updated").textContent=`Updated ${fmt(d.generated_at)} · ${state.items.length} selected items`;render()}
function articleSections(i){return Array.isArray(i.sections)&&i.sections.length?i.sections:(i.primary_section?[i.primary_section]:[])}
function visibleItems(){const q=state.search.trim().toLowerCase();return state.items.filter(i=>{const s=state.section==="All"||articleSections(i).includes(state.section);const h=[i.title,i.summary,i.source,...(i.tags||[]),...articleSections(i)].join(" ").toLowerCase();return s&&(!q||h.includes(q))}).sort((a,b)=>(b.relevance||0)-(a.relevance||0)||new Date(b.published_at)-new Date(a.published_at))}
function countForSection(s){return state.items.filter(i=>articleSections(i).includes(s)).length}
function render(){renderSections();renderNews()}
function renderSections(){const g=document.getElementById("sectionGrid");g.innerHTML=SECTION_ORDER.map(s=>{const active=state.section===s;return `<button class="section-filter ${active?"active":""}" data-section="${esc(s)}"><div class="section-filter-heading"><h2>${esc(s)}</h2><span class="section-count">${countForSection(s)}</span></div><p>${esc(QUESTIONS[s])}</p></button>`}).join("");g.querySelectorAll(".section-filter").forEach(b=>b.addEventListener("click",()=>{state.section=state.section===b.dataset.section?"All":b.dataset.section;render();document.querySelector(".latest-wrap")?.scrollIntoView({behavior:"smooth",block:"start"})}))}
function renderNews(){const items=visibleItems();document.querySelector(".section-title-row h2").textContent=state.section==="All"?"All selected articles":state.section;document.getElementById("resultCount").textContent=`${items.length} article${items.length===1?"":"s"}`;const g=document.getElementById("newsGrid");if(!items.length){g.innerHTML='<div class="empty-state">No article is currently mapped to this topic.</div>';return}g.innerHTML=items.map(i=>`<article class="news-card"><div class="meta"><span>${esc(i.source||"")}</span><span>${fmt(i.published_at)}</span></div><h3>${esc(i.title)}</h3><p>${esc(i.summary||"")}</p><div class="tags">${(i.tags||[]).map(t=>`<span>${esc(t)}</span>`).join("")}</div><div class="bottom"><a href="${esc(i.url)}" target="_blank" rel="noopener noreferrer">Open original source →</a></div></article>`).join("")}
document.getElementById("searchInput").addEventListener("input",e=>{state.search=e.target.value;renderNews()});load();